name: Debug
on:
  push:
    tags:
      - stable-[1-9]+.[0-9]+.[0-9]+
      - testing-[1-9]+.[0-9]+.[0-9]+*

jobs:
  call-remote-workflow:
    uses: droptune/gh-actions-testing-workflows/.github/workflows/get-info.yaml@main
    with:
      secrets:
        repo_secret: ${{ secrets.repo_secret }}
