name: Debug
on:
  push:
    tags:
      - stable-[1-9]+.[0-9]+.[0-9]+
      - testing-[1-9]+.[0-9]+.[0-9]+*
    branches:
	  - dev

jobs:
#  call-remote-workflow:
#    uses: droptune/gh-actions-test-workflows/.github/workflows/get-info.yml@main
#    secrets:
#      repo_secret: ${{ secrets.repo_secret }}
  get-tag:
    name: get tag
    runs-on: ubuntu-latest
    steps:
      - name: "Echo tag"
        id: tag-without-version
        shell: bash
        run: |
          echo REFNAME: ${GITHUB_REFNAME}
          echo "tag_name=${GITHUB_REFNAME%-*}" >> $GITHUB_OUTPUT
        env:
          GITHUB_REFNAME: ${{ github.ref_name }}

      - name: "Get tag name"
        run: echo "The tag name is ${{ steps.tag-without-version.outputs.tag_name }}"
