name: Image
on:
  push:
    tags:
      - stable-[1-9]+.[0-9]+.[0-9]+
      - testing-[1-9]+.[0-9]+.[0-9]+*

jobs:
  name: get-tag
  runs-on: ubuntu-latest
  steps:
    - name: "Echo tag"
      run: echo "Ref: "${{ github.ref_name }}
    - name: "Echo repo"
      run: echo "Repo "${GITHUB_REPOSITORY#*/}
