name: Debug
on:
  push:
    tags:
      - stable-[1-9]+.[0-9]+.[0-9]+
      - testing-[1-9]+.[0-9]+.[0-9]+*

jobs:
  get-tag:
    name: get tag
    runs-on: ubuntu-latest
    steps:
      - name: "Echo tag"
        shell: bash
        run: |
          echo "Ref: "${ GITHUB_REFNAME }
          echo "Repo "${GITHUB_REPOSITORY#*/}
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REFNAME: ${{ github.ref_name }}
