name: Debug
on:
  push:
    tags:
      - stable-[1-9]+.[0-9]+.[0-9]+
      - testing-[1-9]+.[0-9]+.[0-9]+*
    branches:
      - dev

jobs:
#  call-remote-workflow:
#    uses: droptune/gh-actions-test-workflows/.github/workflows/get-info.yml@main
#    secrets:
#      repo_secret: ${{ secrets.repo_secret }}
  get-tag:
    name: get tag
    runs-on: ubuntu-latest
    steps:
      - name: "Echo tag"
        id: tag-without-version
        shell: bash
        run: |
          echo REFNAME: ${GITHUB_REFNAME}
          echo "tag_name=${GITHUB_REFNAME%-*}" >> $GITHUB_OUTPUT
        env:
          GITHUB_REFNAME: ${{ github.ref_name }}

      - name: Echo sha
        shell: bash
        run: echo ${git_sha}
        env:
          git_sha: ${{ github.sha }}

      - name: "Echo base ref"
        shell: bash
        run: |
          echo BASE REF: "${BASE_REF}"
        env:
          BASE_REF: ${{ github.event.base_ref }}

      - name: "Echo branch"
        shell: bash
        run: |
          echo CURRENT_BRANCH ${BASE_REF#refs/heads/}
        env:
          BASE_REF: ${{ github.event.base_ref }}

      - name: "Get tag name"
        run: echo "The tag name is ${{ steps.tag-without-version.outputs.tag_name }}"

      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Get current branch name
        id: get-branch-name
        shell: bash
        run: |
          echo "branch_name=${GITHUB_BASE_REF#/refs/heads/}" >> $GITHUB_OUTPUT
        env:
          GITHUB_BASE_REF: ${{ github.event.base_ref }}

      - name: Set up QEMU
        id: setup-qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: set-up-docker-buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push staging or prod
        id: build-and-push-stable
        if: github.ref_name != 'dev'
        uses: docker/build-push-action@v3
        with:
          tags: empty:${{ github.ref_name }}

      - name: Build and push dev
        id: build-and-push-dev
        if: github.ref_name == 'dev'
        uses: docker/build-push-action@v3
        with:
          tags: empty:dev-${{ steps.get-branch-name.outputs.branch_name }}
